import {SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api, RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const {user} = useUser();
  console.log(user);
  if (!user) return null

  return (
    <div className="flex gap-3 w-full">
      <Image
        src={user.profileImageUrl}
        alt="profile image"
        className="rounded-full h-14 w-14"
        width={56}
        height={56}
      />
      <input type="text" className="bg-transparent grow outline-none" placeholder="What's on your mind?"/>
    </div>
  )
}
type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const {post, author} = props;
  return (
    <div key={post.id} className=" border-b border-slate-400 p-4 flex gap-3">
      <Image
        width={56}
        height={56}
        src={author.profileImageUrl}
        alt="profile image"
        className="rounded-full h-14 w-14"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <span className="">{`@${author.userName} · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>  
  )
}

const Home: NextPage = () => {
  const user = useUser();

  const {data, isLoading} = api.posts.getAll.useQuery();
  console.log(data);

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong 😢😢</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className=" w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-3 flex">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => <PostView {...fullPost} key={fullPost.post.id}/>)}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
